name: Deploy Static site to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-site:
    uses: clawd-cook/workflows/.github/workflows/deploy-pages.yml@da5da395aad07541153b2d0da859a7f8ac183b2e
